apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 18.1.10
    helm:
      values:
        volumePermissions:
          enabled: true
        primary:
          containerSecurityContext:
            readOnlyRootFilesystem: false |
        auth:
          postgresPassword: "guestbook"
          username: "guestbook"
          password: "guestbook"
          database: "guestbook"
        
        primary:
          persistence:
            enabled: true
            size: 2Gi
          
          service:
            ports:
              postgresql: 5432
          
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
        
        metrics:
          enabled: false
        
        # Create a service with a consistent name
        fullnameOverride: "postgresql"
        image:
          registry: docker.io
          repository: postgres
          tag: "16-alpine"

  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
